"""
Aurora PostgreSQL for the IT Helpdesk backend -- replaces the local
Docker Postgres (docker-compose.yml) for a real deployment. Aurora
PostgreSQL 16.4 supports the `vector` extension (same one
migrations/0006_knowledge_chunks_and_vector.sql enables locally against
pgvector/pgvector:pg16), so no schema/migration changes are needed to
move from local dev to this.

Serverless v2, not a fixed provisioned instance: bills per ACU-hour
(0.5-2 ACUs configured below) and scales within that range automatically
-- cheaper than the smallest fixed instance class for a backend this
size, and there's no "right-sizing" guess to get wrong up front.

Public accessibility is a deploy-time choice (`publicly_accessible`
context value, defaulting to True per this project's current need to
run `python -m migrations.run_migrations` directly from a local machine
against this cluster), NOT a permanent architectural decision -- see the
CfnOutput at the bottom and infra/README.md for how to flip it back to
private-only (the recommended state once migrations are done and the
ECS-hosted backend, which reaches this cluster from inside the VPC
either way, is the only thing that needs to).
"""
from aws_cdk import CfnOutput, Duration, RemovalPolicy, Stack
from aws_cdk import aws_ec2 as ec2
from aws_cdk import aws_rds as rds
from constructs import Construct

DB_NAME = "helpdesk"
DB_USERNAME = "helpdesk_admin"
DB_PORT = 5432


class DatabaseStack(Stack):
    def __init__(
        self,
        scope: Construct,
        construct_id: str,
        vpc: ec2.IVpc,
        *,
        publicly_accessible: bool = True,
        allowed_cidr: str | None = None,
        **kwargs,
    ) -> None:
        super().__init__(scope, construct_id, **kwargs)

        # allow_all_outbound=False: a database has no legitimate reason
        # to initiate outbound connections at all -- the default
        # (allow-all egress) is needless extra blast radius on a
        # resource that should only ever be responding to inbound
        # queries, never calling out anywhere itself.
        db_security_group = ec2.SecurityGroup(
            self,
            "AuroraSecurityGroup",
            vpc=vpc,
            description="Aurora PostgreSQL for the IT Helpdesk backend",
            allow_all_outbound=False,
        )

        # Allow anything inside this VPC (concretely: compute_stack.py's
        # Fargate tasks) to reach Aurora on 5432, using the VPC's own
        # CIDR block rather than a direct reference to the Fargate
        # service's security group. A direct SG-to-SG reference would
        # need this stack to import a value FROM ComputeStack, which
        # already depends ON this stack (app.py) for the cluster
        # reference -- CDK correctly refuses that as a cyclic stack
        # dependency. The VPC CIDR has the same practical effect here
        # (nothing else lives in this VPC besides the NAT gateway and
        # the backend service) without the circular reference, and adds
        # no dependency on ComputeStack existing at all -- this stack
        # can deploy on its own.
        db_security_group.add_ingress_rule(
            ec2.Peer.ipv4(vpc.vpc_cidr_block),
            ec2.Port.tcp(DB_PORT),
            "Any resource inside this VPC (the ECS-hosted backend) -- see this comment for why this isn't a direct security-group reference",
        )

        if publicly_accessible:
            # cdk deploy -c aurora_publicly_accessible=true -c aurora_allowed_cidr=<your-ip>/32
            # TEMPORARY, by design (see module docstring): opens 5432 to
            # whatever CIDR is given, defaulting to the whole internet
            # (0.0.0.0/0) if none is -- deliberately loud about that
            # default rather than silently narrowing it, so it's obvious
            # from the deploy output whether this run is actually locked
            # to one IP or wide open. Passing your own /32 instead of
            # accepting the default is strongly recommended even for
            # short-lived testing.
            cidr = allowed_cidr or "0.0.0.0/0"
            db_security_group.add_ingress_rule(
                ec2.Peer.ipv4(cidr),
                ec2.Port.tcp(DB_PORT),
                f"TEMPORARY direct access for running migrations from {cidr} -- "
                f"see database_stack.py's module docstring; revert once migrations are done",
            )

        subnet_type = ec2.SubnetType.PUBLIC if publicly_accessible else ec2.SubnetType.PRIVATE_WITH_EGRESS

        # from_generated_secret: a real, random password, generated by
        # Secrets Manager, never typed by a human or committed anywhere
        # -- same pattern as email_stack.py's InboundEmailSecret.
        # exclude_characters covers the characters that would corrupt a
        # postgresql://user:password@host/db connection string if the
        # generator happened to include them.
        credentials = rds.Credentials.from_generated_secret(DB_USERNAME, exclude_characters='"@/\\ ')

        self.cluster = rds.DatabaseCluster(
            self,
            "AuroraCluster",
            engine=rds.DatabaseClusterEngine.aurora_postgres(version=rds.AuroraPostgresEngineVersion.VER_16_4),
            vpc=vpc,
            vpc_subnets=ec2.SubnetSelection(subnet_type=subnet_type),
            security_groups=[db_security_group],
            credentials=credentials,
            default_database_name=DB_NAME,
            port=DB_PORT,
            writer=rds.ClusterInstance.serverless_v2("Writer", publicly_accessible=publicly_accessible),
            serverless_v2_min_capacity=0.5,
            serverless_v2_max_capacity=2,
            storage_encrypted=True,
            backup=rds.BackupProps(retention=Duration.days(1)),
            # Both of these matter together for the "deploy, test, tear
            # down cheaply" workflow described when this was built:
            # removal_policy=DESTROY sets CloudFormation's DeletionPolicy
            # to Delete instead of the RDS default (Snapshot) -- but RDS
            # clusters have a SEPARATE "take a final snapshot on delete"
            # behavior that DeletionPolicy alone doesn't disable, which
            # is what the explicit property override just below handles.
            # Without both, `cdk destroy` would still leave a snapshot
            # behind, quietly billing storage forever until it's found
            # and deleted by hand.
            removal_policy=RemovalPolicy.DESTROY,
            deletion_protection=False,
        )
        cfn_cluster = self.cluster.node.default_child
        cfn_cluster.add_property_override("SkipFinalSnapshot", True)

        self.database_url_parts = {
            "host": self.cluster.cluster_endpoint.hostname,
            "port": str(DB_PORT),
            "dbname": DB_NAME,
        }

        # Exposed so the CI/CD pipeline (.github/workflows/deploy.yml) can
        # authorize/revoke a scoped, per-run ingress rule for its own
        # runner IP around the migration step, instead of this stack
        # needing to know the runner's IP ahead of time the way the
        # `aurora_allowed_cidr` context value does for a human running
        # migrations from a fixed location.
        CfnOutput(self, "AuroraSecurityGroupId", value=db_security_group.security_group_id)
        CfnOutput(self, "AuroraClusterEndpoint", value=self.cluster.cluster_endpoint.hostname)
        CfnOutput(self, "AuroraClusterPort", value=str(DB_PORT))
        CfnOutput(self, "AuroraDatabaseName", value=DB_NAME)
        CfnOutput(self, "AuroraSecretArn", value=self.cluster.secret.secret_arn)
        CfnOutput(
            self,
            "AuroraPublicAccessNote",
            value=(
                f"publicly_accessible={publicly_accessible}. "
                "Fetch the generated password with: "
                f"aws secretsmanager get-secret-value --secret-id {self.cluster.secret.secret_name} "
                "--query SecretString --output text | python3 -m json.tool"
            ),
        )
