"""
Phase 5A: AWS infrastructure for inbound email ingestion.

    Student --email--> SES --PutObject--> S3 --ObjectCreated--> Lambda --HTTPS--> FastAPI

Every resource here maps to something you could click together by hand in
the AWS Console -- this file just describes the same resources as code.
See the root README's Phase 5 section for the CDK-construct-to-Console
mapping and the full request-flow walkthrough.
"""
import os

from aws_cdk import (
    CfnOutput,
    Duration,
    RemovalPolicy,
    Stack,
)
from aws_cdk import aws_iam as iam
from aws_cdk import aws_lambda as _lambda
from aws_cdk import aws_s3 as s3
from aws_cdk import aws_s3_notifications as s3n
from aws_cdk import aws_secretsmanager as secretsmanager
from aws_cdk import aws_ses as ses
from aws_cdk import aws_ses_actions as ses_actions
from constructs import Construct

LAMBDA_CODE_PATH = os.path.join(os.path.dirname(__file__), "..", "..", "lambda", "email_ingestion")
EMAIL_KEY_PREFIX = "emails/"


class EmailIngestionStack(Stack):
    def __init__(self, scope: Construct, construct_id: str, **kwargs) -> None:
        super().__init__(scope, construct_id, **kwargs)

        # cdk deploy -c fastapi_base_url=https://api.example.com -c it_support_email=it-support@university.edu
        # See the root README for every context value this stack reads and
        # why none of them are hard-coded here.
        fastapi_base_url = self.node.try_get_context("fastapi_base_url") or "https://CHANGE-ME.example.com"
        it_support_email = self.node.try_get_context("it_support_email") or "it-support@university.edu"

        # cdk deploy -c debug_log_email_body=true
        # TESTING ONLY -- off by default. See handler.py's own comment on
        # the log line this gates: logs the full raw email body to
        # CloudWatch, which is deliberately never logged otherwise
        # (phase5.md #11). Never leave this on for a real deployment.
        debug_log_email_body = str(self.node.try_get_context("debug_log_email_body") or "false").lower()

        # --- Part 1: S3 -----------------------------------------------------
        # Encrypted (SSE-S3 -- no extra KMS key to manage for a first
        # implementation), fully private (no inbound student email should
        # ever be one misconfigured bucket policy away from public), and
        # enforcing HTTPS-only access. RemovalPolicy.RETAIN because this
        # bucket holds real (if raw) student correspondence -- an
        # accidental `cdk destroy` should not be able to delete it.
        email_bucket = s3.Bucket(
            self,
            "InboundEmailBucket",
            encryption=s3.BucketEncryption.S3_MANAGED,
            block_public_access=s3.BlockPublicAccess.BLOCK_ALL,
            enforce_ssl=True,
            removal_policy=RemovalPolicy.RETAIN,
        )

        # --- Part 9: the one secret this stack manages ----------------------
        # Generated by AWS, never typed by a human or committed to git.
        # The Lambda is granted read access to this *one* secret only (see
        # below) -- not blanket Secrets Manager access.
        inbound_email_secret = secretsmanager.Secret(
            self,
            "InboundEmailSecret",
            description="Shared secret Lambda sends as X-Webhook-Secret to FastAPI's POST /email/inbound",
            generate_secret_string=secretsmanager.SecretStringGenerator(
                exclude_punctuation=True, password_length=40
            ),
        )

        # --- Part 2: Lambda --------------------------------------------------
        # Plain .py files, no third-party pip dependencies (boto3 ships
        # with the runtime; everything else is standard library) -- so
        # `Code.from_asset` just zips the directory as-is, no bundling
        # Docker image or dependency-layer step required.
        email_ingestion_fn = _lambda.Function(
            self,
            "EmailIngestionFunction",
            function_name="it-helpdesk-email-ingestion",
            runtime=_lambda.Runtime.PYTHON_3_12,
            handler="handler.lambda_handler",
            code=_lambda.Code.from_asset(LAMBDA_CODE_PATH),
            timeout=Duration.seconds(30),
            memory_size=256,
            environment={
                "FASTAPI_BASE_URL": fastapi_base_url,
                "INBOUND_EMAIL_SECRET_ARN": inbound_email_secret.secret_arn,
                "DEBUG_LOG_EMAIL_BODY": debug_log_email_body,
                # AWS_REGION is a Lambda-reserved environment variable
                # (CloudFormation rejects setting it explicitly) -- boto3
                # already resolves it automatically inside the Lambda
                # runtime, so it's never listed here.
            },
        )

        # --- Part 5: IAM -- Lambda execution role ---------------------------
        # `lambda.Function` attaches a default execution role with
        # AWSLambdaBasicExecutionRole automatically -- that managed policy
        # is exactly "CloudWatch Logs" (logs:CreateLogGroup/CreateLogStream/
        # PutLogEvents), scoped to this function's own log group. Nothing
        # else needs to be added for logging.
        #
        # S3 read access is added explicitly and narrowly: s3:GetObject
        # only (no ListBucket, no PutObject, no DeleteObject), and only on
        # the emails/ prefix of this one bucket -- not
        # bucket.grant_read(fn), which would also add broader list/read
        # actions this Lambda never needs. This is the "Lambda execution
        # role" phase5.md Part 5 asks about: permissions the function
        # itself holds when it runs, independent of who is allowed to
        # *invoke* it (that's the resource-based policy below).
        email_ingestion_fn.add_to_role_policy(
            iam.PolicyStatement(
                sid="ReadInboundEmailObjectsOnly",
                actions=["s3:GetObject"],
                resources=[email_bucket.arn_for_objects(f"{EMAIL_KEY_PREFIX}*")],
            )
        )

        # Grants exactly secretsmanager:GetSecretValue on this one secret
        # -- not "read all secrets in this account."
        inbound_email_secret.grant_read(email_ingestion_fn)

        # --- Part 6: S3 -> Lambda invocation ---------------------------------
        # `add_event_notification` does two things at once, which is worth
        # separating explicitly (phase5.md Part 5 asks for this
        # distinction):
        #   1. Configures the bucket to *send* ObjectCreated events to this
        #      Lambda for objects under emails/.
        #   2. Adds a Lambda *resource-based policy* statement -- distinct
        #      from the execution role above -- granting the S3 service
        #      principal (scoped to this bucket's ARN via a SourceArn
        #      condition) permission to invoke this specific function. The
        #      execution role controls "what can this Lambda do"; the
        #      resource-based policy controls "who is allowed to invoke
        #      this Lambda" -- two different policies, attached to two
        #      different sides of the relationship.
        #
        # Prefix-only filter, deliberately no suffix=".eml" -- verified
        # against a real SES-delivered email that this was originally
        # written with a suffix filter, on the (wrong) assumption SES
        # names its S3 objects with a .eml extension. It doesn't: SES's
        # S3 action writes the object key as its own internal message ID
        # with no extension at all (confirmed against a real inbound
        # email: a key like "2l6ogh3ud18i7r8neo5ls2ighlmf1nh6rninei81",
        # nothing after it) -- with the suffix filter in place, real mail
        # could never match this trigger and the Lambda would never run,
        # even though everything else (SES receiving, the S3 write, IAM)
        # was working correctly. A manual test that uploads a
        # self-chosen "test.eml" filename masks this bug completely,
        # which is exactly how it was first written; only a real,
        # SES-delivered email caught it. The one-time
        # AMAZON_SES_SETUP_NOTIFICATION object SES also writes to this
        # prefix when the receipt rule is first configured predates this
        # notification config's existence (S3 event notifications never
        # fire retroactively for objects already present), so removing
        # the suffix filter doesn't risk processing that one as if it
        # were a real email.
        #
        # No recursion risk: this Lambda only ever calls s3:GetObject, never
        # PutObject -- it cannot write a new object into emails/ and
        # re-trigger itself.
        email_bucket.add_event_notification(
            s3.EventType.OBJECT_CREATED,
            s3n.LambdaDestination(email_ingestion_fn),
            s3.NotificationKeyFilter(prefix=EMAIL_KEY_PREFIX),
        )

        # --- Part 7: SES -> S3 ------------------------------------------------
        # A receipt rule with an S3 action. Binding this action inside a
        # ReceiptRule is what adds the necessary *bucket policy* statement
        # -- the third and last permission concept in this stack, distinct
        # from both policies above -- granting the SES service principal
        # (scoped to this AWS account via an aws:Referer/SourceAccount
        # condition CDK adds automatically) s3:PutObject on this bucket.
        # SES needs to *write* here; Lambda only ever *reads* -- two
        # opposite, non-overlapping permissions on the same bucket.
        receipt_rule_set = ses.ReceiptRuleSet(self, "InboundEmailRuleSet")
        receipt_rule_set.add_rule(
            "StoreInboundEmailInS3",
            recipients=[it_support_email],
            scan_enabled=True,  # SES's built-in spam/virus scan
            actions=[
                ses_actions.S3(bucket=email_bucket, object_key_prefix=EMAIL_KEY_PREFIX),
            ],
        )

        # A deployed ReceiptRuleSet is not automatically the *active* one
        # for the account/region -- CDK/CloudFormation has no resource for
        # "set this rule set active" (it's a plain API call, not a
        # provisionable resource). Run once after every deploy that
        # changes this rule set:
        #   aws ses set-active-receipt-rule-set --rule-set-name <name>
        # (the exact name is in this stack's CfnOutput below).

        # --- Outputs, for manual verification/deployment ---------------------
        CfnOutput(self, "EmailBucketName", value=email_bucket.bucket_name)
        CfnOutput(self, "EmailIngestionFunctionName", value=email_ingestion_fn.function_name)
        CfnOutput(self, "InboundEmailSecretArn", value=inbound_email_secret.secret_arn)
        CfnOutput(self, "ReceiptRuleSetName", value=receipt_rule_set.receipt_rule_set_name)
